# Site settings
title: I'm Jwaxy
description: Jwaxy's personal website.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: I am Jwaxy
user_description: Someone who codes in his free time just for fun
user_title: Software Developer
email: jwaxy@proton.me
twitter_username: 
github_username:  jwaxy
#gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
